adjacency: adjacency.o adjacency.h
	gcc -g -ansi -Wall -pedantic -std=c90 adjacency.o -o adjacency
adjacency.o: adjacency.c adjacency.h
	gcc -c -ansi -Wall -pedantic -std=c90 adjacency.c -o adjacency.o 
